### ISSUE TITLE
VNC 

### ISSUE THREAD

**Issue by QuintinSmith334** [Mincka/ha-addons#10]
Hi is it possible to access this plugin from vnc from a other computer or tablet 

i tried using the default ports in the original Firefox docker image with no luck 

Thanks For the assistants

**Comment by Mincka** [comment]
Hi,
Is it you Herman? I saw a recent post with very similar needs on HA Community forum.
I'll try to update the addon based on the changes you've made. Thanks.

**Comment by Shiroe93** [comment]
I second this for the VNC (better if with a password) and the other option in the original container (display resolution, dark mode, full screen with no header etc) in my case I used the original conteiner to access home assistant from an old unsupported ipad 3

**Comment by xvolte** [comment]
Hello
Same here. I got a very old ipad staying around and would love to use this firefox via VNC. 
Is it hard to update? I so the post but it seems to be complex to make the changes in the docker as i m running ha os.

**Comment by Mincka** [comment]
You can know enable ports, kiosk mode, dark mode, set VNC password, resolution, default URL and more in version 1.1.0.

**Comment by xvolte** [comment]
Awesome!
Thanks a lot
