### ISSUE TITLE
Allow access to non-admin users and kiosk mode

### ISSUE THREAD

**Issue by acseven** [Mincka/ha-addons#12]
Hi,
Thanks for this addon, I've been looking for a stable and quick solution to open a local IoT web page and this has solved it!

However, I ended up having to create a local copy of your addon to add the following option to `config.yaml`, which allows non admin users to access ingress (as long as the sidebar button is enabled):
`panel_admin: false`

Would you mind adding this to your addon?

I also modified `startapp.sh` in order to get firefox to run in kiosk mode (i.e. one single page with little to no options), by changing this:

`#exec /usr/bin/firefox "$@" >> /config/log/firefox/output.log 2>> /config/log/firefox/error.log`

into this:

`exec /usr/bin/firefox -kiosk 192.168.1.90 >> /config/log/firefox/output.log 2>> /config/log/firefox/error.log`

Given there are quite a lot of others like me looking for a good solution for a simple kiosk addon in HA, it would be great if you could this as a configuration variable; there are other interesting options for this, one of the main using `-private-window` as well. 

Cheers!

**Comment by Linkek** [comment]
I really would love to see kiosk mode to be an option. And would be cool to be able to make multiple tabs or. Maybe a full size card for dashboard.

I don't know how this docker instance work in this case. And if it's possible to make multiple "kiosk" from one installation of this add-on. But if it's possible, it could open up a lot of cool stuff you could do with it.

**Comment by Mincka** [comment]
You can know enable ports, kiosk mode and default URL in version 1.1.0.
`panel_admin` is also now set to `false`.

**Comment by acseven** [comment]
Thanks for this update, works great! I'll have to keep using my modified version though, as I was able to customize the sidebar icon and description to be more specific to what the kiosk actually displays (instead of "Firefox"). I guess that can't be customised through the addon's UI configuration settings. But again, many  thanks, it will be useful for other uses!
