### ISSUE TITLE
Changing scaling method on the fly only possible once

### ISSUE THREAD

**Issue by bcutter** [Mincka/ha-addons#2]
I noticed that once the scaling mode is set to "Remote resizing", it's not possible to switch back to any other method (scaling stays unchanged). Selecting another one needs a restart of the addon to make it work.

**Comment by Mincka** [comment]
I don't have this behavior. If I switch back from Remote to Local or None, the changes are applied as soon as I resize the window.

**Comment by bcutter** [comment]
Didn't try to resize the window. Is that a workaround? On desktops the browser window stays in maximized mode.

And how to resize a window inside the HA Companion app?

**Comment by Mincka** [comment]
I mean you need to resize the browser window of HA, not Firefox window.
On mobile, the Firefox window is resized if you have rotation enabled and actually rotate the phone (switch between portrait and landscape orientations).

**Comment by bcutter** [comment]
Maybe this helps to better understand the issue - as nothing, even resizing windows or switching from portrait to landscape mode - fixes the scaling:

1. Addon freshly started, scaling method = **local scaling**
![grafik](https://user-images.githubusercontent.com/13799156/233789950-345851e8-fb57-4706-9bad-f8430ed915b4.png)

2. Switched to **remote resizing** (working ✔)
![grafik](https://user-images.githubusercontent.com/13799156/233789987-53226cec-8d09-4057-b350-e77a69ef4991.png)

3. Switched back to **local scaling** (no change ❌)
![grafik](https://user-images.githubusercontent.com/13799156/233790012-cada985b-aa57-408b-a510-77cab0f173b9.png)

4. Resized the window to a different size (where local scaling actually seems to work) and resized it back to the original size (maximized on desktop)
![grafik](https://user-images.githubusercontent.com/13799156/233790086-4983927d-0fb4-4a00-bbbb-30e3a1d4aaa4.png)
--> does not look like in step 1 but still like in 2 or 3 ❌. That's exactly what this issue is about.

**Comment by Mincka** [comment]
If you switch from Remote to Local, it won't return to the previous size and that's expected for me, the "Local" resolution is updated to the "Remote" one when you're switching to "Remote", so when you switch back to "Local", it looks the same.
If I switch from Remove to Local and I resize my browser window, the Firefox window will not be dynamically updated, its resolution stays the same, that's the "Local Scaling" working as expected.

Maybe you can try the upstream container and see if this behavior is related to HA Ingress or noVNC:
https://github.com/jlesage/docker-firefox
