### ISSUE TITLE
installing on home assistant docker

### ISSUE THREAD

**Issue by ivanjx** [Mincka/ha-addons#22]
is there a way to install and integrate the firefox addon with home assistant that is installed as docker container?

**Comment by Mincka** [comment]
Maybe you can just use the base image:
https://github.com/jlesage/docker-firefox

**Comment by ivanjx** [comment]
unfortunately that will require me to expose the web browser separately from HA's gui and authentication

**Comment by Mincka** [comment]
I see. There's no "ingress proxy" yet for this addon, but maybe using  `ingress-proxy` from https://github.com/tux2000/home-assistant-addons/ would already work.

It's a generic ingress proxy that you can configure to point to any internal URL. In that case, you could target the local IP and port of the Firefox add-on.

**Comment by Mincka** [comment]
Sorry, I misread, you cannot use any HA add-on.

How would like to use it? Would not it better for you to use VPN / Tailscale ?

**Comment by ivanjx** [comment]
im currently looking at https://github.com/vouch/vouch-proxy

**Comment by ivanjx** [comment]
yup i can confirm that it works perfectly fine with frigate so using this addon is now irrelevant for me. thank you anyways.

**Comment by Mincka** [comment]
What did you do in the end? Expose `jlesage/docker-firefox` behind `vouch-proxy` with HA authentication as Identity Provider?
Or you expose your individual web applications directly behind `vouch-proxy`?

**Comment by ivanjx** [comment]
originally i am planning to use your addon to expose my frigate instance using home assistant auth since frigate does not have a login system.

vouch proxy is not a reverse proxy like nginx so you have to have nginx first. then in nginx you force all request to be redirected to vouch proxy to check for the auth. if not authenticated yet (by checking the cookie) then it will show the login page from HA.
