### ISSUE TITLE
Which DNS was used?

### ISSUE THREAD

**Issue by aurelien219** [Mincka/ha-addons#23]
Hi,

I used this add-on since few month and it's work like a charm until now (or until my operator breaks something).

I've a problem since a few days when my network provider block some websites (DNS block). I change the DNS provider on my HA system, I can ping the website so DNS was really changed but Firefox can't still open the page. Is it use the system DNS or an other ? 

```
# cat /etc/systemd/resolved.conf 

[Resolve]
DNS=1.1.1.1 8.8.8.8
```

I tryed to change the DNS from my computer and the site is reachable. 

Thank's
Aurelien

**Comment by Mincka** [comment]
Hi,
Try to enable DNS over HTTPS in Firefox to exclude DNS block issues.

![image](https://github.com/Mincka/ha-addons/assets/6184289/aef49c2f-bf6c-4371-b6a0-a2f40797e4fa)
