### ISSUE TITLE
Asian font support

### ISSUE THREAD

**Issue by MaoZ1993** [Mincka/ha-addons#24]
Hi Mincka, Thanks for your contribute. 
This browser saved me from switching between different VPN.

I do encounter some issue when browsing some Asian language webpage, I googled around and found this docker need to add some CJK font to allow Asian font support. But due to the add-on's limitation, I cannot edit the docker settings.

Is that possible if you could integrate the Asian Fonts support into this add-on? Thanks

Ref:
https://github.com/jlesage/docker-firefox/issues/68
https://github.com/linuxserver/docker-mods/issues/274

**Comment by Mincka** [comment]
You can know enable this option in version 1.1.0.

**Comment by MaoZ1993** [comment]
Thanks! It works!
