### ISSUE TITLE
audio support

### ISSUE THREAD

**Issue by kingunlim** [Mincka/ha-addons#27]
hi im loving your addon!
is there a way to enable audio support in the firefox browser?

i access it via vnc on my old ipad
best regards

**Comment by kingunlim** [comment]
maybe anyone knows something to get this to work?

**Comment by Mincka** [comment]
Hi, having the sound on the host where the add-on is running is something that should be possible.
That's mean if you have HA running on HA Yellow or Blue for instance, you could be able to hear the sound using the jack port.

However, if you want to be able to have get the sound on a remote PC that is used to access Firefox through ingress, it requires specific versions of VNC and / or the usage of Pulse Audio client.

A few issues related to audio are open in the upstream project:
https://github.com/jlesage/docker-firefox/issues?q=is%3Aissue+is%3Aopen+audio

**Comment by kingunlim** [comment]
thx for your answer!
so i connect to the firefox docker via an old ipad via vnc, is there something i must configure via the variables?
i saw in the docker config file of your addon that the audio part is uncommented?

**Comment by Mincka** [comment]
I don't think that's possible because you won't be able to run a Pulse Audio client on the iPad.

**Comment by Mincka** [comment]
Audio support is now available through the browser in version 1.3.2.
It's not a fix for your original request but as I explained, I don't think I can do much more for your specific setup.
