### ISSUE TITLE
Cpu/ram usage 

### ISSUE THREAD

**Issue by pergolafabio** [Mincka/ha-addons#29]
Hi, 

I'm using the Firefox add-on to display the HA webpage...
But is there any particular reason why it's using so much cpu/ram when it's idle?

All my other add-ons are like 0,5 or max 1

See screenshot

![Screenshot_20240304-132353](https://github.com/Mincka/ha-addons/assets/43251136/987bb65b-30ed-4065-afff-ec5c7675a4b2)

**Comment by pergolafabio** [comment]
Its increasing now after a few hours:
![image](https://github.com/Mincka/ha-addons/assets/43251136/310227ec-a80e-43d6-ae52-67f570a61063)

**Comment by pergolafabio** [comment]
here is output of top command:

```
➜  ~ docker exec addon_49e24ccc_firefox top -n1
Mem: 3979700K used, 34428K free, 37612K shrd, 44872K buff, 1812608K cached
CPU:  55% usr   5% sys   0% nic  40% idle   0% io   0% irq   0% sirq
Load average: 0.55 0.58 0.63 5/1102 1277
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
  782   683 root     R    3269m  83%   1  10% {Isolated Web Co} /usr/lib/firefox
  683     1 root     S    2933m  74%   0   0% /usr/lib/firefox/firefox --profile
  891   683 root     S    2599m  66%   0   0% {Privileged Cont} /usr/lib/firefox
  838   683 root     S    2588m  66%   0   0% {WebExtensions} /usr/lib/firefox/f
 1046   683 root     S    2569m  65%   0   0% {Web Content} /usr/lib/firefox/fir
 1176   683 root     S    2569m  65%   1   0% {Web Content} /usr/lib/firefox/fir
 1133   683 root     S    2569m  65%   0   0% {Web Content} /usr/lib/firefox/fir
 1211   683 root     S     543m  14%   0   0% {RDD Process} /usr/lib/firefox/fir
  886   683 root     S     517m  13%   0   0% {Utility Process} /usr/lib/firefox
  752   683 root     S     446m  11%   0   0% {Socket Process} /usr/lib/firefox/
  649     1 root     S    23272   1%   1   0% Xvnc -nolisten tcp -nolisten local
  664     1 root     S    11780   0%   0   0% /opt/base/bin/openbox --config-fil
  660   654 root     S     6696   0%   1   0% nginx: worker process
  661   654 root     S     6696   0%   0   0% nginx: worker process
  654     1 root     S     6240   0%   0   0% nginx: master process /opt/base/sb
 1273     0 root     R     1600   0%   0   0% top -n1
    1     0 root     S      980   0%   1   0% /opt/base/sbin/cinit --progname su
```

**Comment by Mincka** [comment]
I guess it depends on what's displayed on your dashboard and the number of tabs open.
There's no particular reason to increase CPU usage when idle, or maybe background Firefox tasks (download of updates).
What are your systems specifications? For the host of HA.

**Comment by pergolafabio** [comment]
Hi, thnx for feedback, there is only 1 tab open, now i tested with url www.google.com, its indeed better

![image](https://github.com/Mincka/ha-addons/assets/43251136/ee7b9849-208e-4cff-b8fc-671a860f620b)


If i make the url from HA , then its eating cpu/ram

even when not logged in into HA , is there anything i can do to finetune this?

![image](https://github.com/Mincka/ha-addons/assets/43251136/c255ef60-fda0-4f0d-be5d-adeb9daf87ca)

**Comment by Mincka** [comment]
Same questions: what's displayed on your dashboard? any camera? what are the specifications of your host system?

**Comment by Mincka** [comment]
Ok, even if it's the login page, this is not a good page to benchmark the add-on because of their useless animation in the background. It's heavily CPU intensive and I also saw that behavior on my setup, with laggy add-on on this specific page.

Can you try on real dashboard if you have the same issue? Your system is ok and should be sufficient for the add-on.

**Comment by Mincka** [comment]
About 23/25% on this login page, indeed...
Between 2 and 10% on one dashboard without cameras.

**Comment by pergolafabio** [comment]
ok, nothing to make it less then :-)
