### ISSUE TITLE
Two mirror effect to infinity

### ISSUE THREAD

**Issue by proasnet** [Mincka/ha-addons#38]
Thanks for a great addon. It helps me manage devices on my local network.
I tried one thing. In firefox I gave the HA address, opened the website itself, and then it started nesting until it went to infinity, which can cause the whole HA system to crash. I recommend curing this effect if possible.
It looked like in an elevator where there are 2 mirrors facing each other.

**Comment by Mincka** [comment]
Hi, 
I know that and also [played with that](https://www.reddit.com/r/homeassistant/comments/12hx4rx/comment/jftboqi/).
This is something that you are not expected to do. You are very aware that you're already in HA.
We cannot block specific URLs in Firefox, and we would not be aware of all the possible URLs that can be used to access to your instance.
