### ISSUE TITLE
Opening the browser always showing itself

### ISSUE THREAD

**Issue by tyanai** [Mincka/ha-addons#40]
Hi,

Seems the docker starts with no errors, on SSL enabled.  However, each time I try to use it, it will open the adds-on in a kiosk mode (although it is set to 0) and with the HA default dashboard in it.

Removing the SSL back no a none secured (setting it back to 0) opens it just fine.

Thanks,

Tal.

**Comment by Mincka** [comment]
Hi,
Did you ever change `FF_KIOSK`?
Can you try if you have the same behavior with the upstream container?
https://github.com/jlesage/docker-firefox

Most of the environment variables are use as-it by the original container.
