### ISSUE TITLE
Add-on not starting

### ISSUE THREAD

**Issue by Supermanenvysme** [Mincka/ha-addons#42]
Add on refusing to start. Initially worked, but now the following error:

[init        ] container is starting...
[cont-env    ] loading container environment variables...
[cont-env    ] APP_NAME: loading...
/init: line 65: can't create /var/tmp/.cont-env-internal: nonexistent directory

**Comment by Mincka** [comment]
Which version? Normal, Edge? Did you try to uninstall and reinstall it again?

**Comment by Supermanenvysme** [comment]
> Owner

both versions, uninstalled, restarted reinstalled, same error
