### ISSUE TITLE
Optional debug port for automation

### ISSUE THREAD

**Issue by miaucl** [Mincka/ha-addons#46]
I tried to open the debug port `--remote-debugging-port=9222` using the `FF_CUSTOM_ARGS` from the base repo: https://github.com/jlesage/docker-firefox

But the addons would need to expose this port before I can connect to it use it for stuff like `playwright` or `selenium`.

Would it be possible to expose this functionality?

**Comment by Mincka** [comment]
Hi, it's added in 1.3.2 but I'm not sure how to use that. I tried to play a little bit the the remote debugging port and the remote debugging address. I see that it's enabled because of the red bar with robot emoji but I did not manage to connect to the debugger. Let me know if that works for you.

**Comment by miaucl** [comment]
The problem is that it only allows connections from localhost (127.0.0.1), not from outside (0.0.0.0). The work around is to use 'socat' to forward to another port, such as https://stackoverflow.com/a/20984766. 

I will have a look at the new version

**Comment by Mincka** [comment]
Ok, on my side I tried with --remote-debugging-address 0.0.0.0, and I also enabled a few flags in about:config related to this, but even with that I did not manage to reach this port from the outside. Hopefully it will be enough for your use case.

**Comment by miaucl** [comment]
> Ok, on my side I tried with --remote-debugging-address 0.0.0.0, and I also enabled a few flags in about:config related to this, but even with that I did not manage to reach this port from the outside. Hopefully it will be enough for your use case.

The remote debugging address is a deprecated flag unfortunately, which does not work anymore. Which is why the `socat` workaround is needed. I'll have a look if I manage to make it work.

**Comment by miaucl** [comment]
Hmm, seems to not work the way I want it to due to following information: https://stackoverflow.com/a/75979086

The `normal` firefox is not working with playwright for automation, the library needs a patched version.

**Comment by Mincka** [comment]
Ok, so I guess I'll revert this additional port in the next release.
