### ISSUE TITLE
[Request] Web Browser for Low Ram

### ISSUE THREAD

**Issue by Tikilou** [Mincka/ha-addons#6]
Hi ! I would thank your for your work, it's very usefull with Home Assistant, i'm using it to access local Tasmota devices used with OpenSprinkler and Home Assistant on Raspberry PI Zero 2W and Raspberry 4.

Actually, there is problem of availability with all theses kind of cards, and my Pi Zero 2W only have 512Mb of ram, and the Pi4 only 1Gb of ram, 2/4/8gb are unavailable.

Could you make the same repository on your github than Firefox, with an very light web browser (like midori, epiphany, dillo...) wich dont need too many ram and can be usable with 512Mb of ram ? 

Actually with firefox, i have to swap and it's very very laggy...

**Comment by Mincka** [comment]
Hi @Tikilou,
I wanted to share a fork of my repo I saw last month but... [it's yours](https://github.com/Tikilou/ha-addons/commits/main). :)
So I guess it did not work? Do you know why?

**Comment by Tikilou** [comment]
Yes, it's mine, but yes, he didn't work, and i'm not enough advanced user to know why, i've only tried to modify somes files directly in github, and it's still continue to launch firefox ^^"
Hope your could help, midori could be a very good alternative to firefox, very light ^^
